### ISSUE TITLE
Broken IDs

### ISSUE THREAD

**Issue by Iseratho** [samanthph/twitter-consp-theory-data#1]
Hi, I would be interested in your dataset for my research.

Unfortunately, most of the (longer) IDs seem to be broken at the moment.
The (variable) amount of trailing zeros in the IDs suggests a conversion/precision error (e.g., if they were stored as a float at some point). 
Thus, simply removing the zeros does not necessarily lead to valid IDs either.

From my own experience: the IDs should always be used as a string and not as numbers.
If the file was created using pandas, there is an issue when loading JSON with big numbers: https://github.com/pandas-dev/pandas/issues?q=is%3Aissue+read_json+bug+is%3Aopen (e.g., https://github.com/pandas-dev/pandas/issues/44684 ). Explicitly loading the IDs as a string should solve the problem.

I would appreciate it if you could look into this issue.
Best regards.

**Comment by samanthph** [comment]
Hello,

Thank you for bringing this to my attention.  I will look into this today
and get back to you.

**Comment by samanthph** [comment]
Hi,

I have the unrounded ID's now.  It seems that some of the tweets are now
deleted so I'm figuring out why not all the ID's are leading to hydrated
tweets.  I will get back to you by Monday.  Thank you for your patience.

Samantha

**Comment by Iseratho** [comment]
Thank you for looking into this issue.
Did you make any progress on fixing it?

**Comment by samanthph** [comment]
Hi Markus,

Thanks for checking in.  I managed to fix the rounded ID's.  Full
disclosure, about 800 of the original 3100 IDs no longer lead to hydrated
tweets.  I manually looked at a sample of these IDs- each tweet has either
been deleted or the account that posted the tweet is suspended.  I suppose
that is a product of considering tweets containing conspiracy theories.
Regardless, I will upload the unrounded IDs to the git repo today.

Please let me know if you run into any other issues!
Samantha

**Comment by samanthph** [comment]
Uploaded!

**Comment by Iseratho** [comment]
Thanks
